### ISSUE TITLE
PhosPir and TMT experiments

### ISSUE THREAD

**Issue by hcadre** [TCB-yehong/PhosPiR#2]
Hi, 
I am wondering whether PhosPir could also be adapted to accept data from TMT-labeled samples? I guess it boils down to question whether PhosPir will be able to handle the "Reporter_intensity_corrected" columns from the corresponding Phospho (STY)site.txt file as input, right? 
Best, 
Hannes

**Comment by TCB-yehong** [comment]
Hi, yes it could take in TMT-labeled samples. There is a "Other" option, if direct "MaxQuant" standard result file is not available. You could format the data in the following way: 

1. File format should be .csv or .xlsx.

2.	The first 6 columns should contain information as follows. Column 1 contains the UniProt protein ID, column 2 contains the protein description, column 3 displays gene name, column 4 shows the phosphorylated amino acid residue, column 5 records the phosphorylation site position within the protein, and column 6 shows the sequence window. The sequence window should have the phosphorylation site in the center position and extend in both directions by at least 7 amino acids. The order of the columns is crucial and should not be randomized.

3.	Column 7 onward should contain sample intensity values. Each column corresponds to 1 sample, and each row corresponds to 1 phosphorylation pattern. Intensity values should not be in log scale.

4.	Missing values should be written as “NA” or 0. Intensity columns should be numeric columns.

Choose "Other" for input option, then choose the formatted file as input for PhosPiR should work.

Or if you like, you could send the first few rows of the Phospho (STY)site.txt file, I can check the formatting to see if it could be input directly to PhosPiR with "MaxQuant" option.

**Comment by hcadre** [comment]
Requirements as described in 3. for sample intensity values are probably difficult to fulfill with the original MaxQuant output since each sample in Phospho (STY).site.txt  is represented by 3 columns (Reporter intensity   corrected 1___1 | Reporter intensity corrected 1___2 | Reporter intensity corrected 1___3 | Reporter intensity corrected 2___1 | Reporter intensity corrected 2___2 ...) for singly, doubly and multiply phosphorylated sites but I can try to use the "expand site table"-function in Perseus squeeze each sample into one column

**Comment by TCB-yehong** [comment]
Hi, PhosPiR should be able to take your Phospho (STY)site.txt file directly. It combine these columns usually from the original Phospho (STY)site.txt file. However if you want to analyze them separately, there is a function in PhosPiR (only for "MaxQuant" input files), called "Expanded phosphorylation count", that works exactly like "expand site table" function from Perseus, where it generates the formatted input for PhosPiR for separated phosphorylated site count.
Yes the format you included is perfect for selecting "Other" as input option! One other thing I wanted to mention is that the imputation step only works when there are at least 4 non-missing values per row (to make sure it's sensible). For the attached example file, imputation couldn't work (if the option is selected, it will automatically redirect you to select another option).

**Comment by hcadre** [comment]
Imputation is not really necessary for many TMT-labeled experiments since the number of missing values is much much lower, compared to label-free measurements. So I skipped the lines containing only "0"s neglecting these p-sites and tried to run the resulting file through PhosPiR. Following grouping of the samples I got up to the step where the Overview Figures should be generated but received an error here:
...
![image](https://user-images.githubusercontent.com/16349515/154518830-74053f54-4291-41d1-a0f8-795e2fc8fad6.png)

**Comment by TCB-yehong** [comment]
Hi,
Did you run PhosPiR from the beginning? This short video includes an example of group setup: https://youtu.be/c7n7yE0DMsA. If you are looking for the specific group setup line in run.R, it's this one: source(paste0(codepth,"inputGeneration.R")), which also includes all other setups. You could also provide the groups with an excel file like in the following example: 
[Phospho (STY)Sites_sample_grouping_order_input_example.csv](https://github.com/TCB-yehong/PhosPiR/files/8095744/Phospho.STY.Sites_sample_grouping_order_input_example.csv)
To provide the excel, you would need to go through the setup line. 
Let me know if something's unclear.

**Comment by hcadre** [comment]
I made a mistake during the grouping of my samples - your comments pointed me to the right path! Thank you very much! Now the annotation step is running.....
